DROP TABLE IF EXISTS PERSONALTRAINER_USER;

CREATE TABLE PERSONALTRAINER_USERDETAIL (
  id BIGSERIAL PRIMARY KEY,
  height NUMERIC NOT NULL,
  weight NUMERIC NOT NULL,
  bodyType TEXT NOT NULL,
  created DATE NOT NULL,
  updated DATE,
  userId BIGINT NOT NULL REFERENCES PERSONALTRAINER_USER
);
