CREATE TABLE USER (
	id VARCHAR GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	surname varchar(255) not null,
	email varchar(255) not null,
	loginname varchar(255) not null,
	hashed_password varchar(255) not null,
	created varchar(255) not null,
	updated varchar(255) not null,
);

insert into PERSON (first_name, last_name) values ('Dave', 'Syer');